Simplified Chinese localization update
TTT-2/TTT2 pull request #1014
Opened 2023-01-05 22:51 UTC by sbzlzh

2023-01-05 22:55 UTC, saibotk commented
@TheOnly8Z or @TEGTainFan would you mind taking a look?

2023-01-06 19:16 UTC, sbzlzh commented
TheOnly8Z does not seem to be involved, TEGTainFan is probably busy

2023-01-06 20:19 UTC, TheOnly8Z commented
Looks like there are some incorrect punctuation usage - parenthesizes, commas and periods should be full-width, e.g:

> 测试，请用全角标点（像这样）。

Instead of 

> 测试, 别用半角标点 (像这样).

I will start a code review and make amendments.

2023-01-06 20:24 UTC, TheOnly8Z requested changes

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.limit_time = "已达到时限. 下一张地图即将加载."
```suggestion
L.limit_time = "达到时间限制。即将加载下一张地图。"
```

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.limit_round = "达到回合数上限. 下一张地图即将加载."
```suggestion
L.limit_round = "达到回合限制。即将加载下一张地图。"
```

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.vis_hint = "按下 {usekey} 键捡起它(仅限侦探)。"
Should not use half-width punctuation.

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.dna_no_killer = "DNA样本无法检索(凶手已离线？)"
Should not use half-width punctuation.

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.corpse_hint = "按下 [{usekey}] 来搜索，用 [{walkkey} + {usekey}] 进行无声搜索。"
Half-width is fine here since it is brackets around a key.

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
>  目前在这张地图上有{weapon}武器生成，{ammo}弹药生成和{player}玩家生成。
```suggestion
目前在这张地图上有 {weapon} 个武器生成点，{ammo} 个弹药生成点和 player} 个玩家生成点。
```

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.menu_server_addons_description = "仅管理员可以对附加插件进行设置。"
Incorrect context.

```suggestion
L.menu_server_addons_description = "服务器端管理员专用的插件设置。"
```

2023-01-06 20:24 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.label_highlight_vip = "突出显示TTT2 VIP"
```suggestion
L.label_highlight_vip = "高亮显示 TTT2 VIP"
```

2023-01-06 20:36 UTC, sbzlzh commented
ok

2023-01-06 22:10 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.round_voting = "投票进行中，新的回合将推迟到 {num} 秒后开始... "
extra space

2023-01-06 22:11 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.help_targetid_info = "目标高亮TargetID是显示在实体和玩家下面的信息。可以在通用菜单启用全局颜色。"
Probably better to keep the parenthesizes here.

2023-01-06 22:11 UTC, TheOnly8Z commented
Looks good, just a a few small things and we can merge.

2023-01-06 22:14 UTC, sbzlzh commented
All right

2023-01-06 22:19 UTC, sbzlzh commented
@TEGTainFan Suggest you help to modify the Traditional Chinese

2023-01-06 22:22 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.help_targetid_info = "目标高亮(TargetID)是显示在实体和玩家下面的信息。可以在通用菜单启用全局颜色。"
```suggestion
L.help_targetid_info = "目标高亮（TargetID）是显示在实体和玩家下面的信息。可以在通用菜单启用全局颜色。"
```

2023-01-06 22:25 UTC, sbzlzh commented on lua/terrortown/lang/zh_hans.lua
> +L.help_targetid_info = "目标高亮(TargetID)是显示在实体和玩家下面的信息。可以在通用菜单启用全局颜色。"
All right

2023-01-06 22:30 UTC, TheOnly8Z requested changes

2023-01-06 22:30 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.label_confirm_detective_only = "限制尸体的确认只限于警察角色"
```suggestion
L.label_confirm_detective_only = "只允许警察角色确认死者"
```

2023-01-06 22:30 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.label_inspect_detective_only = "将搜尸的范围限定为只限于警察角色"
```suggestion
L.label_inspect_detective_only = "只允许警察角色搜查尸体"
```

2023-01-06 22:30 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.label_haste_minutes_per_death = "每位玩家死亡的时间奖励（分钟）"
```suggestion
L.label_haste_minutes_per_death = "玩家死亡给予的额外时间（分钟）"
```

2023-01-06 22:30 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.help_karma = "人品值是用来减少无差别击杀的。玩家开始时有一定量的人品值，当他们伤害/杀死队友时就会失去人品值。他们失去的数值取决于他们伤害或杀死的人的人品值。较低的人品值会减少给予的伤害。"
```suggestion
L.help_karma = "玩家有一定量的初始人品值，伤害/杀死队友时会失去人品。失去的数值取决于他们伤害或杀死的人的人品值，对方人品越低，损失的人品越低。"
```

2023-01-06 22:30 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.help_karma_strict = "如果更严格人品值被启用，伤害惩罚会随着人品值的减少而更快增加。当它关闭时，让人品值保持在800以上时的伤害惩罚是非常低的。启用严格模式使人品值在阻止任何不必要的击杀方面发挥更大的作用。而禁用它则导致一个更'宽松'的游戏范围，人品值只影响那些不断击杀队友的玩家。"
```suggestion
L.help_karma_strict = "如果严格人品模式被启用，伤害惩罚会随着人品值的减少快速增加。非严格模式下，人品值保持在 800 以上时的伤害惩罚非常低。启用严格模式使人品值在阻止任何不必要的击杀方面发挥更大的作用，而禁用它则导致一个更宽松的游戏范围，人品系统只会影响不断击杀队友的玩家。"
```

2023-01-06 22:31 UTC, TheOnly8Z commented
Changed some wording. Should be good to merge after these are fixed.

2023-01-06 22:32 UTC, sbzlzh commented
Wait a minute, got it

2023-01-07 02:32 UTC, TheOnly8Z approved these changes
LGTM for zh_hans.

2023-01-08 04:06 UTC, saibotk approved these changes

2023-01-13 10:03 UTC, TimGoll approved these changes
Thanks a lot! Interesting to see that chinese doesn't seem to have whitespace chracters, does it?

2023-01-13 10:03 UTC, merged