Update Simplified Chinese Translation
TTT-2/TTT2 pull request #1022
Opened 2023-02-20 14:59 UTC by sbzlzh

@TheOnly8Z What do you think?What is your translation of 1864 and 1865?

2023-02-25 06:13 UTC, TheOnly8Z requested changes

2023-02-25 06:13 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.hudeditor_chat_hint4 = "[TTT2][INFO] 按[RMB] -> 'Close'来退出HUD编辑器！"
```suggestion
L.hudeditor_chat_hint4 = "[TTT2][INFO] 按 [RMB] -> 'Close' 来退出HUD编辑器！"
```

2023-02-25 06:13 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.sb_rank_tooltip_streamer = "Streamer"
```suggestion
L.sb_rank_tooltip_streamer = "主播"
```

2023-02-25 06:13 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.sb_rank_tooltip_heroes = "TTT2 Heroes"
```suggestion
L.sb_rank_tooltip_heroes = "TTT2 英雄"
```

2023-02-25 06:13 UTC, TheOnly8Z commented on lua/terrortown/lang/zh_hans.lua
> +L.guide_nothing_title = "这里还没有消息!"
```suggestion
L.guide_nothing_title = "这里暂时什么都没有！"
```

2023-02-25 06:14 UTC, TheOnly8Z commented
Posted my recommended changes.

2023-02-25 17:18 UTC, sbzlzh commented
all right

2023-02-25 17:19 UTC, sbzlzh commented
Is there more?

2023-02-25 17:57 UTC, TheOnly8Z commented
LGTM.

2023-02-25 17:58 UTC, sbzlzh commented
ok

2023-02-25 22:24 UTC, saibotk approved these changes
Thank you :)

2023-02-26 07:42 UTC, Histalek approved these changes
:+1:

2023-02-26 07:43 UTC, merged