allow reading files from data_static
TTT-2/TTT2 pull request #1057
Opened 2023-09-28 18:36 UTC by EntranceJew

not tested extensively, feature still in dev for gmod itself

2023-09-29 17:41 UTC, saibotk commented
Nice!
Is there any documentation on what is allowed in the folder or how did you come up with this?
E.g. is there any standard folder for the map entspawnscript json to follow the same path in the data_static folder?

2023-09-29 17:54 UTC, EntranceJew commented
I did some testing on the `Dev` branch to confirm that there was no auto-overlay behavior, I was prompted to look into it after I saw this commit in the [gmod discord](https://commits.facepunch.com/461197)

There was some discussion about it but ultimately Rubat said:
> it's just a folder you file.Read from, omg you guys
which revealed it was likely just going to exist along-side `data/`, which makes sense with my testing.
(no `DATA_STATIC` context, no reading `data/file.txt` in place of `data_static/file.txt` or vice-verse, etc)

Ultimately means there is no convention and the fall-through behavior is up to us to enforce if we desire it. Otherwise it's just another folder we can't write to like `maps/`. It probably only obeys the filetype restrictions that `gmad.exe` enforces globally.

I use gmpublisher so I haven't actually experimented with what `gmad.exe` will or won't reject just yet.

2023-09-30 13:52 UTC, saibotk commented
Okay, so there is nothing really special about it?

Then another question, what benefits do we get from adding the new folder?

And are these two the only parts that actually read from the data folder? I dont remember currently but i could imagine there being more.

2023-09-30 20:05 UTC, EntranceJew commented
The only thing special about it is that it isn't ignored by GMA like data is, so people can create addons out of their weapon placements similar to all the rearm script addons that are out there for TTT.

Now people can distribute weapon spawn rebalance packs or button fix configs for maps specifically using TTT2's files, because even with the `ttt2.fgd` you can't specify a random grenade spawn which is a small thing but could be huge for how someone's got their configurations laid out.

![image](https://github.com/TTT-2/TTT2/assets/5711436/01a5f80e-bee8-42bc-a5e5-dd564efc3eb1)
These are all the places I see file.Read being run, so if there's something else reading files somewhere, I'm imagining it's going through one of these locations.

The only one I didn't change is reading the TTT1 text files included inside `maps/` which, since it's legacy behavior, is something better suited for that step in the process before it gets converted to the TTT2 spawn file.

2023-10-01 09:34 UTC, saibotk commented
Alright sounds sensible, thanks for explaining this in detail!

2023-10-01 09:34 UTC, saibotk approved these changes

2023-10-01 11:15 UTC, Histalek requested changes
So does this mean that server owners can now setup entspawnscripts that only affect TTT2(or rather terrortown) and don't mess with other game modes?
That's neat.

2023-10-01 11:15 UTC, Histalek commented on lua/ttt2/libraries/entspawnscript.lua
> +			return utilJSONToTable( fileRead(fullDir, "GAME") )
This should be `DATA` instead of `GAME`, right?

```suggestion
			return utilJSONToTable( fileRead(fullDir, "DATA") )
```

2023-10-01 11:15 UTC, Histalek commented on gamemodes/terrortown/entities/entities/ttt_traitor_button/init.lua
> +	modTime = modTime <= lastRead and (not file.Exists(path, "DATA") and (lastRead + 1)) or file.Time("data_static/" .. path, "DATA")
There should be no `data_static/` here to retain the old behaviour, correct?

```suggestion
	modTime = modTime <= lastRead and (not file.Exists(path, "DATA") and (lastRead + 1)) or file.Time(path, "DATA")
```

2023-10-02 01:09 UTC, EntranceJew commented
> So does this mean that server owners can now setup entspawnscripts that only affect TTT2(or rather terrortown) and don't mess with other game modes? That's neat.

Yes, totally. And excellent catches. Subconsciously I think I wanted to just force it to read from "data/" as "GAME" and fallback to "data_static/" as "GAME" but that wouldn't work for writes, and got distracted. I appreciate the oversight for situations like this.

![image](https://github.com/TTT-2/TTT2/assets/5711436/dc8f6bcd-41d1-4559-9f41-9c208d40b687)
I was also able to pack the files with gmad in the dev branch, although I'm not able to test reading a packed gma from the addons folder by itself at the moment, but I do know that you can always read anything inside `garrysmod/` as "GAME" so it isn't that big of a deal.

![image](https://github.com/TTT-2/TTT2/assets/5711436/7b9e5830-7fb5-48db-9a36-89214e6fcba6)


At least, I was able to prove that `data/` is still not whitelisted:
![image](https://github.com/TTT-2/TTT2/assets/5711436/2d4b4a44-f632-4099-b22f-2ddb3b75489e)

2023-10-02 06:53 UTC, Histalek approved these changes
Definitely a nice addition. Thank you very much!

2023-10-02 06:54 UTC, merged