Entity Bringdown volume 2
TTT-2/TTT2 pull request #1198
Opened 2023-12-14 09:01 UTC by TimGoll

Brought more entities from base TTT into TTT2. Modified the code a bit so that it adheres to our coding style, but nothing else was changed.

- targetID integration was improved
- fixed targetID hints (legacy TTT) only working for players and corpses

2023-12-16 22:32 UTC, saibotk commented on gamemodes/terrortown/entities/weapons/weapon_ttt_push.lua
> +			 surface.SetDrawColor(255, 0, 0, 155)
```suggestion
				surface.SetDrawColor(255, 0, 0, 155)
```

2023-12-16 23:15 UTC, saibotk requested changes

2023-12-17 12:33 UTC, TimGoll commented on gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
> +		if activator:IsActiveDetective() and activator:CanCarryType(WEAPON_EQUIP) then
probably a good idea. Only public policing roles should be able to pick it up

2023-12-17 12:34 UTC, TimGoll commented on gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
> +		wep.fingerprints[#wep.fingerprints + 1] = prints
Honestly no idea. I took this as is from TTT. If you think this is a problem, I can investigate it

2023-12-18 18:34 UTC, saibotk commented on gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
> +		wep.fingerprints[#wep.fingerprints + 1] = prints
Would be good, this seems like an error and we should check that before we include this into our codebase.

2023-12-18 18:59 UTC, EntranceJew commented on gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
> +		wep.fingerprints[#wep.fingerprints + 1] = prints
I encountered this before while working on a tweaked version of a knife, I'm fairly confident it is an error, as the code should more than likely read:
```lua
wep.IsDropped = true
wep.fingerprints = table.Copy( self.fingerprints or {} )

self:Remove()

wep:Spawn()
```

I think they were confused by the prospects of `self:Remove()` destroying `self.fingerprints` instantly, and were distracted by copying by reference the table and potentially not its data and forgot to iterate it. Or they were going to add it to the player stack but didn't use the same pattern as the health station. Pretty much every item in a fingerprints table is meant to be a Player, so, this should change.

2023-12-19 10:33 UTC, Histalek approved these changes

2023-12-19 15:15 UTC, TimGoll commented on gamemodes/terrortown/entities/entities/ttt_knife_proj.lua
> +		wep.fingerprints[#wep.fingerprints + 1] = prints
done

2023-12-27 11:00 UTC, EntranceJew approved these changes
i pulled down the files and compared the new ones to `Facepunch/garrysmod`:

things I assume are intentional:
 - leaving `ttt_c4/cl_init.lua` (C4 / Bomb UI) upstream still
 - all the grenades remaining upstream (grenade rework pending)
 - `ttt_weapon_check` remaining upstream
 - `ttt_carry_handler` (not utilized by `weapon_zm_carry`) 

weapons that still only exist on the upstream:
 - `weapon_ttt_c4`
 - `weapon_ttt_defuser`
 - `weapon_ttt_flaregun`
 - `weapon_ttt_health_station`
 - `weapon_ttt_radio`
 - `weapon_ttt_sipistol`
 - `weapon_ttt_stungun`
 - `weapon_ttt_unarmed`

2023-12-27 12:52 UTC, TimGoll commented on gamemodes/terrortown/entities/entities/ttt_cse_proj.lua
> +		local ent = near[i]
That's true. It is slightly faster to define the variable outside the loop and just update the value on each iteration. In our codebase we never use that approach though. Therefore I decided to change that here. To keep it consistent.

2023-12-27 12:53 UTC, TimGoll commented
About the missing entities: They could be part of volume 3. Imho it is better to keep them seperate to make the review easier

2023-12-27 12:57 UTC, EntranceJew commented
> About the missing entities: They could be part of volume 3. Imho it is better to keep them seperate to make the review easier

Absolutely, I was just making note since I had the files pulled down for comparison.

2024-01-08 04:13 UTC, saibotk approved these changes

2024-01-08 04:13 UTC, merged