fixes #1240: the binoculars can now function
TTT-2/TTT2 pull request #1254
Opened 2023-12-24 06:12 UTC by EntranceJew

they still functioned but now they don't throw errors

2023-12-24 13:02 UTC, TimGoll commented
Is the error because SetZoom interferred with the ironsight zoom?

2023-12-24 13:02 UTC, TimGoll approved these changes

2023-12-24 19:26 UTC, EntranceJew commented
> Is the error because SetZoom interferred with the ironsight zoom?

yes

2023-12-27 13:14 UTC, Histalek requested changes

2023-12-27 13:14 UTC, Histalek commented on CHANGELOG.md
> +- Fixed typo in binoculars DataTable refactor
```suggestion
- The binocular zoom now uses a DataTable that is not already used by its weaponbase
```

This describes what was fixed a bit better. This certainly was not only a typo :D

2023-12-27 13:21 UTC, Histalek approved these changes

2023-12-27 13:35 UTC, merged