Indent Subsettings
TTT-2/TTT2 pull request #1277
Opened 2024-01-05 12:35 UTC by TimGoll

Subsettings are now indented to make it easier to spot which settings are related. The master/slave and enable/disable system was also added to helpboxes.

![image](https://github.com/TTT-2/TTT2/assets/13639408/cd63b94e-999f-4547-a7f5-1805fc351178)
![image](https://github.com/TTT-2/TTT2/assets/13639408/aa57ed68-b5e2-4215-b7e6-5a8cdd4875ee)
![image](https://github.com/TTT-2/TTT2/assets/13639408/cd7b97a9-2d77-4ee4-b7f0-3865131e9757)

2024-01-05 12:44 UTC, saibotk requested changes
I like these changes! 

Just some minor renaming stuff

2024-01-05 12:44 UTC, saibotk commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
> +-- @param Panel slave
```suggestion
-- @param Panel master
```

2024-01-05 12:44 UTC, saibotk commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dlabel_ttt2.lua
> +function PANEL:GetMargin()
Usually margin means top, left, right, bottom.

So I'd suggest renaming this to clarify that this is an indentation margin

2024-01-05 12:44 UTC, saibotk commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua
> +-- @param Panel slave
```suggestion
-- @param Panel master
```

2024-01-05 12:44 UTC, saibotk commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/dpanel_ttt2.lua
> +function PANEL:GetMargin()
Same here

2024-01-05 13:07 UTC, saibotk approved these changes

2024-01-06 09:43 UTC, ZenBre4ker approved these changes
LGTM.

As a note, I personally would try to get away from calling things master/slave. So here it could be parent or controller. So for example when the parent is deactivated, the element itself is deactivated.

2024-01-06 10:14 UTC, TimGoll commented
> LGTM.
> 
> As a note, I personally would try to get away from calling things master/slave. So here it could be parent or controller. So for example when the parent is deactivated, the element itself is deactivated.

This change would break other addons though, so I'm not a big fan of that. But in general I see your point here

2024-01-06 10:14 UTC, merged