Equipment Caching: Rework
TTT-2/TTT2 pull request #1424
Opened 2024-02-18 20:16 UTC by TimGoll

Fixes #1403 
Probably also fixes #1091 (to confirm)

This is a draft as of now as I am not on my PC and can therefore not test it yet. But if there is no major oversight, it should already work.

There was also a hook that was called for weapons. I did not add it yet as it seems really specific. If you think it should stay in there, I'll keep it.

2024-02-19 11:06 UTC, TimGoll commented
This should fix the issue @EntranceJew was experiencing. Please confirm

2024-02-19 11:22 UTC, saibotk approved these changes
Very nice!

2024-02-19 11:35 UTC, TimGoll commented
> Looking good so far. Gonna check in detail at home.
> 
> Im only wondering if this is shopeditor only or if this actually should be done for shop or other parts as well. Because then I would move this to another namespace like shop or equipment related.

The shop UI already uses this, the shop backend has its own handling. Maybe one can unify this, but probably not in this PR

2024-02-20 17:32 UTC, ZenBre4ker requested changes

2024-02-20 17:32 UTC, ZenBre4ker commented on gamemodes/terrortown/gamemode/client/cl_equip.lua
> -function TTT2CacheEquipMaterials(item)
This function is used in sh_main after a hotreload of a weapon you changed.

2024-02-20 18:41 UTC, ZenBre4ker approved these changes
Fixed the only error I saw. Otherwise looking good and works for me.

2024-02-20 18:43 UTC, merged