Revert player iterator
TTT-2/TTT2 pull request #1500
Opened 2024-03-31 18:25 UTC by TimGoll

partially reverts #1453

Not sure if this is the best solution or if we should still keep some player.Iterator() calls. Feel free to discuss.

2024-03-31 18:59 UTC, EntranceJew commented
Not all of these cases are trying to modify the table, wouldn't make sense to revert them all across the board

2024-03-31 20:35 UTC, saibotk requested changes

2024-03-31 20:35 UTC, saibotk commented on gamemodes/terrortown/gamemode/server/sv_weaponry.lua
> +local playerGetAll = player.GetAll
Remove this one
```suggestion
```

2024-03-31 20:35 UTC, saibotk commented on gamemodes/terrortown/gamemode/shared/sh_player_ext.lua
> +local playerGetAll = player.GetAll
```suggestion
```

2024-03-31 20:35 UTC, saibotk commented on lua/ttt2/extensions/util.lua
> +    local plys = player.GetAll()
```suggestion
    local plys = playerGetAll()
```

2024-03-31 20:35 UTC, saibotk commented on lua/ttt2/extensions/util.lua
> +    local plys = player.GetAll()
```suggestion
    local plys = playerGetAll()
```

2024-03-31 20:35 UTC, saibotk commented on lua/ttt2/libraries/entspawnscript.lua
> +        plys = plys or player.GetAll()
```suggestion
        plys = plys or playerGetAll()
```

2024-03-31 20:35 UTC, saibotk commented on lua/ttt2/libraries/entspawnscript.lua
> +        plys = plys or player.GetAll()
```suggestion
        plys = plys or playerGetAll()
```

2024-04-11 19:16 UTC, TW1STaL1CKY commented
Sorry to prod, is this fix able to be merged soon? 😄
At the moment the master branch isn't playable without this fix - certain actions like placing a C4 causes the gamemode to completely break

2024-04-11 19:37 UTC, TimGoll commented
I'm out of town for this and the next week as well. If someone finishes it, then we can merge it

2024-04-11 20:45 UTC, saibotk approved these changes

2024-04-12 06:37 UTC, Histalek approved these changes

2024-04-12 06:38 UTC, merged