Add convar to prevent players without credits from being able to see credits on a body
TTT-2/TTT2 pull request #1504
Opened 2024-04-07 03:17 UTC by nike4613

The one question left for this is whether to change the default. Currently, this PR defaults to the previous behavior (all players can see credits, except in mode 2), but it seems to me like player expectations would favor not seeing credits by default.

2024-04-07 09:12 UTC, Histalek reviewed
@TimGoll could you comment on this? i think you had a reason for showing credits on a body by default

Additionally, wouldn't this be a usecase for the `TTTBodySearchPopulate` hook?

2024-04-07 09:16 UTC, nike4613 commented
> Additionally, wouldn't this be a usecase for the `TTTBodySearchPopulate` hook?

That hook does not appear to be able to remove things which have already been added to the UI. Credits are added here:
https://github.com/TTT-2/TTT2/blob/d4df150769d45e231fc146502758f9044d637516/gamemodes/terrortown/gamemode/client/cl_search.lua#L292-L301
while the hook is invoked here:
https://github.com/TTT-2/TTT2/blob/d4df150769d45e231fc146502758f9044d637516/gamemodes/terrortown/gamemode/client/cl_search.lua#L309
well after the info items have been added.

2024-04-07 11:55 UTC, TimGoll commented
OK, I'd prefer this to be serverside instead of client side, if you want to hide the data, then it should be done in `bodysearch.AssimilateSceneData()`:

https://github.com/TTT-2/TTT2/blob/cb48c43464e4522ed868676b03f3fabce4d1e3e0/lua/ttt2/libraries/bodysearch.lua#L267

That way a detective search would still push the data to everyone.

In my opinion it should be visible to everyone so it is harder for traitors etc to snatch the credits without anyone noticing it.
However this special case here might have to be handled differently then. My implementation seems a bit hacky anyway:

https://github.com/TTT-2/TTT2/blob/cb48c43464e4522ed868676b03f3fabce4d1e3e0/gamemodes/terrortown/gamemode/server/sv_corpse.lua#L293-L294

On the hook: I'm aware that it currently doesn't worky anymore to remove/edit stuff. It is something I did not consider when reworking the UI. I only anticipated addons adding custom data. We should probably introduce a serverside hook that can modify the data, it should be probably right here between the two lines in the middle:

https://github.com/TTT-2/TTT2/blob/cb48c43464e4522ed868676b03f3fabce4d1e3e0/gamemodes/terrortown/gamemode/server/sv_corpse.lua#L296-L301

All in all I like your change here, but I don't like the implementation. This change would be a bit more complex then your implementation, but it should still be doable. If you don't want to do it, you can wait until I'm back at home at the end of the month and I'll take a look at it

2024-04-07 21:10 UTC, nike4613 commented
> In my opinion it should be visible to everyone so it is harder for traitors etc to snatch the credits without anyone noticing it.

That's actually kinda the point of the change-- that's a whole interesting metagame that should at least be an option. I generally agree that filtering should be done serverside as much as possible, but for my intended behavior, that would require sending different data to each client, which I suspect will get very complex and error-prone very quickly.

If we do add the option for detective search to push the data everywhere, I'd want that to be a separate cvar, *in addition* to the cvar I've already added.

2024-04-08 00:07 UTC, saibotk approved these changes

2024-04-08 00:09 UTC, saibotk commented
Serverside would be better but since it seems like mode 2 also just does it on the client i think we should change this in another pr.
Otherwise thanks for the comprehensive code and comments, appreciate your work!

2024-04-08 15:29 UTC, TimGoll requested changes
I guess having it clientside is fine for now. But please put the new language strings at the end of the file, similar to how it is done in other PRs. If you scroll down to the end of the file, you'll understand what to do

2024-04-08 15:29 UTC, TimGoll commented on lua/terrortown/lang/en.lua
> +When players with credits (detectives, traitors, survivalist, etc.) die, their credits can be picked up by other players that can use credits.
We tend to call them "shopping roles" in code and documentation, maybe you can change the wording a bit here

2024-04-08 15:29 UTC, TimGoll commented on lua/ttt2/libraries/bodysearch.lua
> +                (cvInspectConfirmMode:GetInt() == 2 or cvCreditsVisibleToAll:GetInt() == 0)
```suggestion
                (cvInspectConfirmMode:GetInt() == 2 or not cvCreditsVisibleToAll:GetBool())
```

2024-04-08 20:00 UTC, TimGoll approved these changes
LGTM, that you very much

2024-04-08 20:01 UTC, merged