Language: Russian language update
TTT-2/TTT2 pull request #708
Opened 2021-01-04 12:56 UTC by scientistnt

I simply translated almost all strings which weren't translated.

2021-01-04 13:08 UTC, saibotk commented
Thank you for your contribution :rocket: 

@Satton2 could you give this translation a look, to get a second opinion, as none of us sadly does understand Russian.

2021-01-04 13:35 UTC, Satton2 commented
> Thank you for your contribution 
> 
> @Satton2 could you give this translation a look, to get a second opinion, as none of us sadly does understand Russian.
> 
> PS: Make sure to add a line to the `CHANGELOG.md` file ;)

Sure. Will do that within 1-2 days, okay? Btw, could you assign me to this PR if possible?

2021-01-04 13:44 UTC, saibotk commented
@Satton2 Thank you, take your time. And i assigned you, just needed you to comment, otherwise i cannot assign you :+1:

2021-01-04 18:56 UTC, Satton2 commented
@scientistnt 
Should I wait a day or more so you can complete editing your translation? Maybe you forgot something else? ;)

When you will be sure that your translation is done, let me know, and I will find some time to review it.

2021-01-04 19:41 UTC, scientistnt commented
> @scientistnt
> Should I wait a day or more so you can complete editing your translation? Maybe you forgot something else? ;)
> 
> When you will be sure that your translation is done, let me know, and I will find some time to review it.

I'm never sure about anything, but the localization seems to be finished and ready for review (i really hope i won't need to change anything again soon).

2021-01-04 22:24 UTC, Satton2 commented
@scientistnt 
> I'm never sure about anything, but the localization seems to be finished and ready for review (i really hope i won't need to change anything again soon).

It's sad that "you never sure about anything". Anyway, you will definitely need to change your translation after my review ;)

Btw, have you synchronized it with my (official) translation of TTT? Make sure that all non-modified strings of TTT are translated in the same way in TTT2.

Also, I hurriedly review your translation and saw that you translated "addon" as "аддон" which is wrong and must be changed to "дополнение". Make sure to synchronize your translation with the official Russian translation of the game.

2021-01-08 22:07 UTC, Satton2 requested changes
Finally, I got some time to make this review.

@scientistnt Please, change all these strings when you will be able, and this pull request will be ready for the merge.

**Note**: If you have some questions about the requested changes, feel free to ask.

2021-01-10 10:46 UTC, Satton2 commented on gamemodes/terrortown/gamemode/shared/lang/ru.lua
>  --L.submenu_appearance_vskin_title = "VSkin"
```suggestion
L.submenu_appearance_vskin_title = "Скин интерфейса"
```

2021-01-10 10:49 UTC, Satton2 commented on gamemodes/terrortown/gamemode/shared/lang/ru.lua
> +L.dna_tid_impossible = "Сканирование невозможно"
```suggestion
L.dna_tid_possible = "Сканирование возможно."
L.dna_tid_impossible = "Сканирование невозможно."
```

2021-01-10 10:56 UTC, Satton2 commented
TTT2 team, this PR currently relies on changes in the following PR request: https://github.com/TTT-2/TTT2/pull/710
Review that PR first.

2021-02-06 18:20 UTC, Satton2 approved these changes
Since https://github.com/TTT-2/TTT2/pull/710 is now merged, I approve these changes.
Thank you for your work!

Please update the PR to resolve the conflicts. Also, please move the changelog line to the "Changed" section.

2021-02-06 18:38 UTC, saibotk approved these changes

2021-02-06 18:39 UTC, Histalek approved these changes

2021-02-06 18:40 UTC, merged