French translation improvement
TTT-2/TTT2 pull request #807
Opened 2021-05-14 23:44 UTC by MisterClems

Improvement of the french translation and translation of the new line (Round end screen)

2021-05-15 00:33 UTC, Alf21 requested changes
Just some format related issues

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.karma_dmg_other = "Votre Karma est à {amount}. De ce fait , tous les dégâts que vous infligerez seront réduits de {num}%"
```suggestion
L.karma_dmg_other = "Votre Karma est à {amount}. De ce fait, tous les dégâts que vous infligerez seront réduits de {num}%"
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.decoy_pickup_wrong_team = "Vous ne pouvez pas le ramasser , car il appartient à une autre team"
```suggestion
L.decoy_pickup_wrong_team = "Vous ne pouvez pas le ramasser, car il appartient à une autre team"
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.door_locked = "Cette porte est verrouillée"
```suggestion
L.door_locked = "Cette porte est verrouillée."
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.desc_event_bodyfound_headshot = "Le joueur a été tué par un tir dans la tête.."
```suggestion
L.desc_event_bodyfound_headshot = "Le joueur a été tué par un tir dans la tête."
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.search_eyes = "En utilisant vos compétences de détective, vous avez identifié la dernière personne qu'il a vue : {player}. Serait-ce le tueur, ou une coïncidence ?"
```suggestion
L.search_eyes = "En utilisant vos compétences de détective, vous avez identifié la dernière personne qu'il a vue: {player}. Serait-ce le tueur, ou une coïncidence?"
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.search_eyes = "En utilisant vos compétences de détective, vous avez identifié la dernière personne qu'il a vue : {player}. Serait-ce le tueur, ou une coïncidence ?"
Same above with `:`

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.search_words = "Quelque chose vous dit que quelques-unes des dernières paroles de cette personne étaient : '{lastwords}'"
```suggestion
L.search_words = "Quelque chose vous dit que quelques-unes des dernières paroles de cette personne étaient: '{lastwords}'"
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.body_call = "{player} appelle un Détective sur le corps de {victim} !"
```suggestion
L.body_call = "{player} appelle un Détective sur le corps de {victim}!"
```

Same 3 times below

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.round_traitors_more = "Traitres, voici vos alliés : {names}"
```suggestion
L.round_traitors_more = "Traitres, voici vos alliés: {names}"
```

2021-05-15 00:33 UTC, Alf21 commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +L.win_traitor = "Les Traitres ont gagné !"
```suggestion
L.win_traitor = "Les Traitres ont gagné!"
```

Same 2 times below

2021-05-15 08:49 UTC, TimGoll reviewed
Looking through the lang, it seems like there is always a space in front of puctuation marks. Is this a thing in french? Or is this bad practice? While it isn't something that you introduced, we'd really appreciate it, if you could remove these spaces (at least if it is bad practice in French).
Just just Strg+F to find and replace

2021-05-15 08:49 UTC, TimGoll commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
>  L.search_kills2 = "Vous avez trouvé une liste de meurtres avec les noms suivants :"
```suggestion
L.search_kills2 = "Vous avez trouvé une liste de meurtres avec les noms suivants:"
```

2021-05-15 08:49 UTC, TimGoll commented on gamemodes/terrortown/gamemode/shared/lang/fr.lua
> +Tuez tout le monde pour gagner !
```suggestion
Tuez tout le monde pour gagner!
```

2021-05-15 11:41 UTC, MisterClems commented
> Looking through the lang, it seems like there is always a space in front of puctuation marks. Is this a thing in french? Or is this bad practice? While it isn't something that you introduced, we'd really appreciate it, if you could remove these spaces (at least if it is bad practice in French).
> Just just Strg+F to find and replace

Yeah thats my bad gonna fix this

2021-05-15 12:17 UTC, MisterClems commented
Okey is fix all should be good

2021-05-15 12:21 UTC, TimGoll approved these changes
Thanks, looks good to me

2021-05-19 08:27 UTC, TimGoll commented
you probably want to add this to the changelog as well. Something like "updated french translation (by MisterClems)"

2021-05-19 11:17 UTC, MisterClems commented
> you probably want to add this to the changelog as well. Something like "updated french translation (by MisterClems)"

Done.But not sure if i have write in on the good section .

2021-05-20 16:51 UTC, merged