F1 menu: rolelayering integration
TTT-2/TTT2 pull request #815
Opened 2021-05-29 09:48 UTC by TimGoll

Integrate the rolelayering UI in the F1 menu

2021-06-10 08:06 UTC, saibotk requested changes

2021-06-10 08:06 UTC, saibotk commented on gamemodes/terrortown/gamemode/shared/sh_rolelayering.lua
> -		net.WriteUInt(data, ROLE_BITS) -- ROLE_NONE = 3 is reserved and here used to indicate as a baserole request. If a valid baserole is given, the subrole list is requested. For further information, se
This comment should appear in a @ note annotation

2021-06-10 08:06 UTC, saibotk commented on lua/terrortown/menus/gamemode/administration/rolelayering.lua
> +		PrintTable(slf.layerList)
Remove prints

2021-06-10 08:07 UTC, TimGoll commented on gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
> +function SKIN:PaintDragSenderTTT2(panel, w, h)
Then I have to rename the sender and receiver as well, because the draw call name reflects the element name

2021-06-10 08:13 UTC, saibotk commented on gamemodes/terrortown/gamemode/client/cl_vskin/default_skin.lua
> +function SKIN:PaintDragSenderTTT2(panel, w, h)
Please do so

2021-06-10 08:15 UTC, TimGoll commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/ddragsender_ttt2.lua
> +	for i = 1, #children do
no, they are both slightly different, therefore sharing doesn't work unfortunately

2021-06-10 08:26 UTC, TimGoll commented on gamemodes/terrortown/gamemode/client/cl_vskin/vgui/ddragreceiver_ttt2.lua
> +			{droppedPnl.subrole}
since this is in the rolelayringreceiver I don't see how I should make this more generic

2021-06-10 09:05 UTC, saibotk approved these changes
Awesome work :)

2021-06-15 16:03 UTC, Alf21 approved these changes
Very great and clean PR! Thanks!

2021-06-15 18:17 UTC, merged