update japanese translate
TTT-2/TTT2 pull request #947
Opened 2021-11-27 06:37 UTC by westooooo

2021-11-28 17:32 UTC, saibotk requested changes

2021-11-28 17:32 UTC, saibotk commented on lua/terrortown/lang/ja.lua
> +チームキルが発生した場合は、さらにペナルティが適用されます。"
```suggestion
L.help_karma_ratio = "両者が同じ陣営にいる場合に、カルマを加害者から差し引く量を計算するためのダメージ比率。チームキルが発生した場合は、さらにペナルティが適用されます。"
```

2021-11-29 00:21 UTC, saibotk requested changes

2021-11-29 00:21 UTC, saibotk commented on lua/terrortown/lang/ja.lua
> +L.label_armor_dynamic = 動的アーマー"
```suggestion
L.label_armor_dynamic = "動的アーマー"
```

2021-11-29 03:58 UTC, westooooo commented on lua/terrortown/lang/ja.lua
> +L.label_armor_dynamic = 動的アーマー"
oh... I missed it... Thanks!

2021-11-29 03:59 UTC, westooooo commented
I fixed it.

2021-11-29 03:59 UTC, saibotk approved these changes
Thank you very much 🥳

2021-11-29 09:31 UTC, ZenBre4ker approved these changes
No clue about japanese. Wont check them with google translator 😆 But structure looks alright. Thank you.

2021-11-29 11:41 UTC, merged