Corrected incorrect translation
TTT-2/TTT2 pull request #975
Opened 2022-06-30 12:14 UTC by sbzlzh

2022-06-30 13:03 UTC, TimGoll approved these changes
You don't have to close and reopen your pullrequest. You can just edit the last one. But this one is good now.

2022-07-01 06:16 UTC, Histalek requested changes
Besides my comment on the changelog this looks good

2022-07-01 06:16 UTC, Histalek commented on CHANGELOG.md
> -  - This hook can be used to allow custom usergroups through these checks
Could you please re-add these lines?

2022-07-02 04:04 UTC, sbzlzh commented on CHANGELOG.md
> -  - This hook can be used to allow custom usergroups through these checks
ok

2022-07-02 04:07 UTC, sbzlzh commented on CHANGELOG.md
> -  - This hook can be used to allow custom usergroups through these checks
Now it has been added

2022-07-02 05:35 UTC, Histalek approved these changes

2022-07-02 05:35 UTC, merged