Roles: Fix hotreloadability of Gamemode
TTT-2/TTT2 pull request #986
Opened 2022-08-20 16:45 UTC by ZenBre4ker

TTT2 should now be able to be hotreloaded again. At least it doesnt throw errors anymore and seems to work.

2022-08-20 16:47 UTC, ZenBre4ker commented
For an unkown reason roleList written as RoleList doesnt work. I couldnt find anything in our or the original terrortown code, that uses that. Maybe I broke a certain addon, that doesnt go over out roles.GetList() function. Not sure.

2022-08-20 16:59 UTC, ZenBre4ker commented
Ah found one, the roles debugger changes it. Testing now if removing the addon and local suffices to fix hotreload.

btw, cant change this to a draft or dont I just see the button?

2022-08-20 17:54 UTC, ZenBre4ker commented
Okay, the rename is not necessary, that was because of the addon. But the idea with local and global didnt make sense anyways. I used the same pattern we use for other modules and just moved it to an internal table. Therefore if something is colliding with roles, it's more clear than a random global variable RoleList.

It hotreloads now faster, as the roles dont need to be initialized again.

2022-08-20 22:10 UTC, saibotk requested changes

2022-08-20 22:10 UTC, saibotk commented on CHANGELOG.md
> +- Fixed hotreload of TTT2 due to roles library not global
Adjust this to the new purpose of the patch

2022-08-21 07:41 UTC, Histalek approved these changes

2022-08-21 09:01 UTC, saibotk approved these changes

2022-08-21 09:20 UTC, TimGoll approved these changes
> It hotreloads now faster, as the roles dont need to be initialized again.

This probably also means that a hotreload no longer breaks the role ID sync, doesn't it?

2022-08-21 10:41 UTC, ZenBre4ker commented
That I didnt check specifically, but in theory it keeps now the same information on both sides. the game at least still works after hotreload.

2022-08-21 10:41 UTC, merged